version: "3.9"
services:
  web_server:
    container_name: web_server
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
  database_server:
    container_name: database_server
    image: mariadb:latest
    ports:
      - 3306:3306
